[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Bryan Koen <bryan.koen@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "3.1.0"
actix-rt = "1.1.1"

[dev-dependencies]
reqwest = "0.10.9"
tokio = "0.2.22"